name: dotnet project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore 
        working-directory: ConsoleApp1/

      - name: Build solution
        run: dotnet build --no-restore
        working-directory: ConsoleApp1/

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ConsoleApp1/
